# Generated by Django 5.1.4 on 2024-12-21 22:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('bridge_id', models.CharField(default='B000', max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bridges',
            },
        ),
    ]
